modLoader="javafml"
loaderVersion="[47,)"
license="GPL-3.0"

[[mods]]
modId="playersync_travelersbackpack_compat"
version="${mod_version}"
displayName="PlayerSync Traveler's Backpack Compatibility"
description='''
Compatibility module that enables PlayerSync to synchronize Traveler's Backpack data across multiple servers.
This includes backpack inventory, fluid tanks, crafting inventory, and all settings.
'''
authors="PlayerSync Compat Team"
displayURL="https://github.com/mlus-asuka/PlayerSync"

[[dependencies.playersync_travelersbackpack_compat]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.playersync_travelersbackpack_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.playersync_travelersbackpack_compat]]
    modId="playersync"
    mandatory=true
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.playersync_travelersbackpack_compat]]
    modId="travelersbackpack"
    mandatory=true
    versionRange="[9.0.0,)"
    ordering="AFTER"
    side="BOTH"
